common/Cargo.toml
terminal/Cargo.toml

`cargo deny check` is complaining about missing license fields on our end:
```
error[L003]: rad-common = 0.1.0 is unlicensed
error[L003]: rad-terminal = 0.1.0 is unlicensed
```
https://github.com/radicle-dev/radicle-upstream/runs/5557014675?check_suite_focus=true#step:5:338

Add missing license fields to common and terminal crates

---

Cargo.lock
common/Cargo.toml

We remove the transitive `openssl-sys` from `rad-common` so that binaries using this crate don’t link against `openssl` since this creates problems on macOS.

Remove openssl-sys dependency from rad-common

---

Cargo.lock
common/Cargo.toml
common/src/ethereum.rs
common/src/ethereum/walletconnect.rs
ens/src/lib.rs

Currently in `Cargo.toml` it's using:
```
walletconnect = { git = "https://github.com/xphoniex/walletconnect-rs", branch = "v0.1.0", features = ["qr"] }`. 
```
which is in my own personal github. Might be helpful to move this to `radicle-dev`, before merging. I changed the types in original package and since author is not responsive, not sure we can merge it in.

Add support for WalletConnect in `rad ens`

---

auth/src/lib.rs
common/src/profile.rs

Fixes https://github.com/radicle-dev/radicle-cli/issues/77.
Fixes https://github.com/radicle-dev/radicle-cli/issues/72.

rad-auth: Handle non-active existing profile(s)

---

Cargo.lock
auth/Cargo.toml
auth/src/lib.rs

Allows doing this, for easier password input:
```
pass radicle/auth | rad-auth
```
where `pass` is https://www.passwordstore.org/ or a similar command line-accessible password manager.

Allow for piping password to rad-auth

---

.github/workflows/release.yml
Cargo.lock
Cargo.toml

Fix missing shared libraries problem on M1 Macs: libssl and libusb.
~~A workaround in libusb-sys has been implemented.  The bug is yet to be reported upstream to libusb.  It's to do with missing libobj.a static library on new versions of macOS.  libusb pkg-config .pc file seems to be assuming they're still there.~~
~~Once the issue is resolved upstream, the workaround in libusb-sys will be removed.~~
According to my understanding, the static build of libusb1-sys on macOS fails because of [a bug in rustc](https://github.com/rust-lang/rust/issues/96943).
IMO, it's best if we maintain a version of libusb1-sys with a workaround (referenced in this PR via `patch.io-crates`) until a rustc fix gets released.

Fix missing shared libraries problem on M1 Macs

---

common/src/person.rs
common/src/project.rs

This PR tries to resolve from the `person.payload()` the `Ens` extension and adds it to the `PeerIdentity` and `PeerInfo`
We need this PR to merge for the issue listing, where we want to resolve a ENS name from a Radicle URN.

common: Add ENS name to PeerIdentity and PeerInfo

---

.gitignore
common/src/cobs/shared.rs

This commit introduces the `serialize_reactions` function which is being
used in the `reactions` field in the `Comment` struct.
To be able to convert `Comment` struct to JSON and return them e.g. in
the http-api we need to convert the
`char` into `String` during serialization.
Signed-off-by: Sebastian Martinez <sebastinez@me.com>

common: Serialize char keys in Comment::reactions

---

issue/src/lib.rs
terminal/src/io.rs

Allows adding emoji reactions as string to a comment specified by its number,
being 0 the root comment.
**TODO:**

rad-issue: Add `rad issue reaction`

---

Cargo.toml

This profile significantly reduces the size of release binaries. As an example `rad-gov` is now only 5.8 MB, down from 20 MB.
We can also use `upx --best --lzma <bin>` and get up to 70% more compression on the binary. Basic testing shows around 200ms added to startup time, which depending on the use case might or might not be worth it.

Add release profile to Cargo.toml

---

patch/src/lib.rs
scripts/contributor-workflow-setup.sh

Use '--message' to set the patches title and description on creation to reduce required human intervention.  The description field is also made optional.

Support message flags for patch creation

---

init/src/lib.rs

Set the default project name as the project's base folder filepath instead of the current working directory rad-clone is run from.

clone: Correct the default project name

---

track/src/lib.rs

Reduce code by pushing conditional logic to determining the sync's seed argument.

track: dry up track syncing

---

comment/src/lib.rs
patch/src/lib.rs
review/src/lib.rs
terminal/src/patch.rs

Update '--comment' and '--review' to use the '--message' option the same way as patch where additional '--message' arguments are appended together.

Make '--message' consistent across commands

---

gov/Cargo.toml

Add the 'ethereum' feature to radicle-terminal to fix a compile time
error.
Fixes issue #196

gov: fix compile time error due to dep error

---

common/src/git.rs
common/src/lib.rs
common/src/project.rs
common/src/seed.rs

Use common::git in place of the git2 module in many cases.  Git2 is re-exported by common::git as the project's git library.

Reduce import complexity for git mod

---

checkout/src/lib.rs
common/src/project.rs
track/src/lib.rs

Communicate to the user when a new git remote is added, on its own line.
References issue #159

track,checkout: inform user about new git remote

---

patch/src/lib.rs

Reduce noise for the user by reducing patch list information to more relevant information.

patch: show only local branches on list

---

scripts/contributor-workflow-setup.sh

Improve the scripts clarity by using long arguments for all commands.

contributor-workflow: use long command arguments

---

README.md

As per [Homebrew docs](https://docs.brew.sh/Taps):
> Any location and any protocol that Git can handle is fine, although non-GitHub taps require running brew tap --force-auto-update <user/repo> to enable automatic updating.

Tell homebrew to auto update the Radicle tap

---

Cargo.lock
inspect/Cargo.toml
inspect/src/lib.rs

Signed-off-by: Miss M <MissM_signed@protonmail.ch>
Taking initial cheap shot at it - replacing with equally not-active crate
Bonus: one less dependency to ansi_term - this uses colored crate instead
json-color dependency tree:
```
color v0.1.0 (/home/radicle/play/color)
└── json-color v0.7.1
├── colored v1.9.3
│   ├── atty v0.2.14
│   │   └── libc v0.2.132
│   └── lazy_static v1.4.0
├── serde v1.0.144
└── serde_json v1.0.85
├── indexmap v1.9.1
│   └── hashbrown v0.12.3
│   [build-dependencies]
│   └── autocfg v1.1.0
├── itoa v1.0.3
├── ryu v1.0.11
└── serde v1.0.144
```

Replace colored_json with json-color

---

Cargo.lock
common/Cargo.toml
inspect/Cargo.toml

Signed-off-by: Miss M <MissM_signed@protonmail.ch>
This PR resolves two below security advisories:
[RUSTSEC-2020-0159](RUSTSEC-2020-0159), [RUSTSEC-2020-0071](https://rustsec.org/advisories/RUSTSEC-2020-0071) - When doing env & time same time - it's not thread safe
Chrono from 0.4.20 has a new maintainer and did a lot of fixes including RiR localtime_r :partying_face: 
time 0.1 in turn is brought by chrono "oldtime" feature that is "optional" (but default) chrono dependency
`default = ["clock", "std", "oldtime", "wasmbind"]` -> `oldtime = ["time"]`
But time 0.1 was included via common & inspect as chrono was imported with default features
I've set the features explicitly leaving out `oldtime` that is not considered thread safe and `wasmbind` we don't need either
By specifying the feature …

Bump Chrono to 0.4.22 and remove time 0.1

---

Cargo.lock
auth/src/lib.rs
common/src/test.rs
scripts/contributor-workflow-setup.sh
terminal/Cargo.toml
terminal/src/io.rs

Closes https://github.com/radicle-dev/radicle-cli/issues/213.

auth: Read passphrase from env var or stdin

---

common/src/project.rs
remote/src/lib.rs
rm/src/lib.rs
terminal/src/lib.rs
terminal/src/remote.rs
untrack/src/lib.rs

Remove the projects rad remote for the peer being untracked.  This is to aid cleaning up and undoing the effects of the 'track' command.
When run from outside a project context via external commands, like 'rad-rm', the cleanup step is skipped.
#159

untrack: cleanup the peer's rad remote

---

Cargo.lock
common/Cargo.toml

Signed-off-by: pinkforest <36498018+pinkforest@users.noreply.github.com>
Closes #218  - Can open another issue to get rid of the git2 OpenSSL dependency completely
This changes to vendored latest OpenSSL and libgit2 via git2 dependency
By default when building something that brings openssl-sys, the underlying OpenSSL C-library is detected by way of opportunistic detection from system where ever it is built from source - whether static .a or dynamic .so object for the linker.
Unless certain rather fickly manual environment variables have been set - it's been derived from the system the thing is built in -
**For the user-built binaries from source**
These OpenSSL libraries in the underlying build system can be out of date - if they are installed that is - and it can be pure luck if the …

Add vendored openssl, libgit2

---

Cargo.lock
Cargo.toml

Avoid creating local branch references for tracking branches.  They are redundant, being already represented by the remote tracking branches.
Recent changes to radicle-link add the improvement.  The 'future's dependencies must be updated to the update.

clone: reduce number of local branches

---

rm/src/lib.rs

The intended usage of `rad rm <urn | profile-id>` (in conjunction with `rad auth`) was a bit unclear as the concepts of profiles and identities require deeper technical knowledge.
With this PR `rad rm` needs to be called with a `peer-id` instead of a `profile-id`. This change is also inline with the upcoming protocol update that makes increased usage of Peer IDs.  
Some users got the internal error message `missing field 'subject'` when passing a URN that does not point to a project. This is now also handled more gracefully.

rm: Remove profile with peer id

---

Cargo.lock
Cargo.toml
account/Cargo.toml
cli/Cargo.toml
common/Cargo.toml
ens/Cargo.toml
gov/Cargo.toml
reward/Cargo.toml

Signed-off-by: pinkforest <36498018+pinkforest@users.noreply.github.com>
Fixes #248 
$ cargo update -p ethers
```
Updating crates.io index
warning: skipping duplicate package `tests` found at `/home/foobar/.cargo/git/checkouts/radicle-link-009c17032bc5eda9/99f4255/bins/tests`
Updating git repository `https://github.com/radicle-dev/radicle-keystore.git`
Updating git repository `https://github.com/radicle-dev/walletconnect-rs`
Updating aead v0.4.3 -> v0.5.1
Updating auto_impl v0.5.0 -> v1.0.1
Updating base64ct v1.5.0 -> v1.0.1
Adding bitvec v1.0.1
Updating blake2 v0.9.2 -> v0.10.4
Updating bytes v1.1.0 -> v1.2.1
Updating cargo_metadata v0.14.2 -> v0.15.0
Updating chacha20 v0.8.1 -> v0.9.0
Updating chacha20poly1305 v0.9.0 -> v0.10.1
Adding cipher v0.4.3
Removing coins-bip32 v0.3.0
Removing …
```

Unblock portability issues caused by sha2-asm and bump ethers

---

scripts/contributor-workflow-setup.sh

Fix script to reflect recent changes to the auth command.  It now requires Peer IDs in place of Profile IDs.

contributor-workflow: Use Peer ID for persons

---

common/src/identity.rs

Describe errors for Peer ID to avoid cryptic errors directly relating to decoding it.

elaborate radicle url parsing error

---

auth/src/lib.rs

Running `rad auth` when no ssh-agent exists succeeds and when you run any other `rad` command you'll be asked to re-enter password. This is confusing and a warning would be helpful when running `auth`.

rad-auth: Add warning for when `ssh-agent` is not running
