- Cargo.lock
- Cargo.toml
- proof-generator/Cargo.toml
- proof-generator/USAGE
- proof-generator/src/lib.rs
- proof-generator/src/main.rs
This PR replaces #5 
Please see discussions and reviews there.
> Add proof creation CLI

- Cargo.lock
- Cargo.toml
- auth/Cargo.toml
- auth/src/args.rs
- auth/src/main.rs
- common/Cargo.toml
- common/src/keys.rs
- common/src/lib.rs
- common/src/person.rs
- common/src/profile.rs
- terminal/Cargo.toml
- terminal/src/lib.rs
Re-implements parts of stale #18.
> Introduces new libraries and implements rad-auth

- Cargo.lock
- Cargo.toml
- common/Cargo.toml
- common/src/keys.rs
- common/src/lib.rs
- common/src/project.rs
- init/Cargo.toml
- init/src/main.rs
Re-implements parts of stale #18.
Depending on https://github.com/radicle-dev/radicle-client-tools/pull/21.
> Implements rad-init.

- Cargo.lock
- Cargo.toml
- common/Cargo.toml
- common/src/lib.rs
- common/src/profile.rs
- common/src/project.rs
- common/src/seed.rs
- publish/Cargo.toml
- publish/src/main.rs
- terminal/src/lib.rs
Re-implements parts of stale #18.
Depends on #22.
> Implements rad-publish

- Cargo.toml
- checkout/rad-checkout.1.adoc
- rad.1.adoc
- sync/rad-sync.1.adoc
> Update man pages

- clone/src/lib.rs
- common/src/seed.rs
- pull/src/lib.rs
- push/src/lib.rs
- src/bin/rad-push.rs
- sync/src/lib.rs
We try to support pushing of single branches.
> Improve push and sync

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
These changes are now released as the v0.5.1 tag but aren't in master, hence this PR.
> Tiny release hotfix

- .github/workflows/actions.yml
- Cargo.toml
[Before](https://github.com/radicle-dev/radicle-cli/actions/runs/2225929322): 30m 11s
[After](https://github.com/radicle-dev/radicle-cli/actions/runs/2232944858): 9m 30s
> Speed up main CI job

- Cargo.lock
- auth/src/lib.rs
- checkout/src/lib.rs
- clone/src/lib.rs
- common/src/keys.rs
- common/src/lib.rs
- common/src/signer.rs
- common/src/test.rs
- ens/src/lib.rs
- init/src/lib.rs
- ls/src/lib.rs
- remote/src/lib.rs
- rm/src/lib.rs
- src/bin/git-remote-rad.rs
- sync/src/lib.rs
- terminal/Cargo.toml
- terminal/src/lib.rs
- track/src/lib.rs
- untrack/src/lib.rs
When not available, the user is prompted for a passphrase.
> Make ssh-agent optional

- common/src/cobs/issue.rs
- common/src/seed.rs
- remote/src/lib.rs
- sync/src/lib.rs
- terminal/src/lib.rs
- terminal/src/sync.rs
- track/src/lib.rs
> Verify signed refs on fetch

- Cargo.lock
- Cargo.toml
- path/Cargo.toml
- path/src/lib.rs
- src/bin/rad-path.rs
> rad-path: Initialize

- Cargo.lock
- Cargo.toml
- auth/src/lib.rs
- common/Cargo.toml
- common/src/cobs/patch.rs
- common/src/cobs/shared.rs
- common/src/git.rs
- common/src/lib.rs
- common/src/patch.rs
- common/src/project.rs
- gov/src/lib.rs
- issue/src/lib.rs
- merge/Cargo.toml
- merge/src/lib.rs
- patch/src/lib.rs
- push/src/lib.rs
- remote/src/lib.rs
- self/src/lib.rs
- src/bin/rad-merge.rs
- sync/src/lib.rs
- terminal/src/format.rs
- terminal/src/io.rs
- terminal/src/lib.rs
- terminal/src/patch.rs
- terminal/src/spinner.rs
- track/src/lib.rs
- track/src/options.rs
> COB patches :corn: (Part 2.) 

- clone/src/lib.rs
- common/src/identity.rs
- common/src/lib.rs
- common/src/project.rs
- pull/src/lib.rs
- sync/src/lib.rs
Closes https://github.com/radicle-dev/radicle-cli/issues/130
> rad-sync: Make person docs syncable

- common/src/cobs/issue.rs
- issue/src/lib.rs
This PR adds the following commands and functionalities
- `rad issue state <id> [--close | --open] [--solved]`
Allows the user to change the state of an issue from `open` to `closed, give a `CloseReason` by using the `--solved` flag, and re-open the issue if necessary.
> rad-issue: Close and re-open issues

- Cargo.lock
- Cargo.toml
- comment/Cargo.toml
- comment/src/lib.rs
- common/src/cobs/issue.rs
- common/src/cobs/patch.rs
- issue/src/lib.rs
- src/bin/rad-comment.rs
Closes https://github.com/radicle-dev/radicle-cli/issues/135.
> rad-comment: Initial commit

- common/src/cobs/patch.rs
- merge/src/lib.rs
- src/bin/git-remote-rad.rs
> Update to rust-1.62

- remote/src/lib.rs
Fail with a message instead of silently failing when an unknown remote peer is removed with the 'rm' sub-command.
Issue #159
> remote: report error when removing unknown peer

- .github/workflows/actions.yml
Offers a modest but a noticeable improvement:
Before: 11m 30s (https://github.com/radicle-dev/radicle-cli/runs/7283232192?check_suite_focus=true)
After: 8m 16s (https://github.com/radicle-dev/radicle-cli/runs/7299582628?check_suite_focus=true)
> Add sccache to CI

- patch/src/lib.rs
Show branch names when listing patches, or nothing when none are present.  This gives the following output:
```
Update README hnrkkqa8n56 R0 f092fb4(change-readme,rad/change-readme) ahead 1, behind 0
└── opened by hnrkd471zrxzjgct4gestio35ai7wnhq67yeo 30 minutes ago
```
> Show branch names when listing patches

- Dockerfile
Signed-off-by: Miss M <MissM_signed@protonmail.ch>
> Add Dockefile for radicle-cli

- Dockerfile
- README.md
Signed-off-by: Miss M <MissM_signed@protonmail.ch>
> Re-organise Dockerfile bin ref

- checkout/src/lib.rs
- reduce nesting where possible
- better express peer selection through vector pattern matching to help visualize how vector length maps to the result.
> checkout: improve clarity

- Cargo.lock
- common/src/keys.rs
- common/src/profile.rs
- rm/Cargo.toml
- rm/src/lib.rs
> rad-rm: Implement profile removal

- README.md
* Assume that users mostly want to use the CLI and guide them to the getting started page
* Make contribution opportunities more prominent
* Funnel support inquiries to the designated channels
* Provide appealing screenshot
* Create and link usage guide inspired by `contribution-workflow-setup.sh`
> Onboarding: Improve README

- .github/workflows/release.yml
Signed-off-by: Adam Szkoda <adaszko@gmail.com>
> Build M1 native binary in CI
